[package]
name = "ranged_integers"
version = "0.1.0"
authors = ["disiamylborane"]
edition = "2018"
license-file = "LICENSE"

description = "An integer type restricted to a compile-time defined range driven by const generics"
repository = "http://github.com/disiamylborane/ranged_integers/"
